CREATE DATABASE IF NOT EXISTS flask_db;
USE flask_db;

CREATE TABLE IF NOT EXISTS users (
    id       INT          AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50)  NOT NULL UNIQUE,
    email    VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,   -- Stores bcrypt/Werkzeug hash
    grade    VARCHAR(10)  DEFAULT NULL -- Set by admin only; students cannot edit
);

-- To assign a grade, run as admin:
-- UPDATE users SET grade = 'A' WHERE username = 'alice';

-- Example seed row (password column must hold the hashed value generated by Flask):
-- INSERT INTO users (username, email, password, grade) VALUES ('admin', 'admin@college.edu', '<hash>', 'A+');